server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gulshan131/my-spring-cloud-config.git
          default-label: main
          skipSslValidation: true
          search-paths:
            - 'calc-economics'
            - 'repo-batch'